"""Initial schema: shows, seasons, episodes, artwork, publish runs, catalogue.

Written by hand rather than autogenerated so the parts that matter -- the two
partial unique indexes and the pg_trgm search index -- are explicit and
reviewable instead of being whatever the autogenerator felt like emitting.

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Substring search over catalogue titles without a sequential scan.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("role", sa.String(16), nullable=False, server_default="editor"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("role in ('editor','admin')", name="ck_users_role"),
    )

    op.create_table(
        "shows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(160), nullable=False, unique=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("synopsis", sa.Text()),
        sa.Column("section", sa.String(64)),
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.String(64)),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("default_language", sa.String(16)),
        sa.Column("status", sa.String(16), nullable=False, server_default="draft"),
        sa.Column("sort_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("status in ('draft','published')", name="ck_shows_status"),
    )
    # The publish job's driving query is `WHERE status = 'published'`.
    op.create_index("ix_shows_status", "shows", ["status"])
    # The CMS list and the catalogue build both order inside a section.
    op.create_index("ix_shows_section_sort", "shows", ["section", "sort_index"])
    # `categories @> '{music}'` for the category filter.
    op.create_index(
        "ix_shows_categories_gin", "shows", ["categories"], postgresql_using="gin"
    )

    op.create_table(
        "seasons",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "show_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("shows.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(255)),
        sa.UniqueConstraint("show_id", "season_number", name="uq_seasons_show_number"),
        sa.CheckConstraint("season_number >= 0", name="ck_seasons_number_nonneg"),
    )
    op.create_index("ix_seasons_show", "seasons", ["show_id"])

    op.create_table(
        "episodes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "season_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seasons.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("synopsis", sa.Text()),
        sa.Column("duration_seconds", sa.Integer()),
        sa.Column("language", sa.String(16), nullable=False),
        sa.Column("content_group", sa.String(160)),
        sa.Column("status", sa.String(16), nullable=False, server_default="draft"),
        sa.Column("video_url", sa.String(1024)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("status in ('draft','published')", name="ck_episodes_status"),
        sa.CheckConstraint(
            "duration_seconds is null or duration_seconds > 0",
            name="ck_episodes_duration_positive",
        ),
        sa.UniqueConstraint(
            "season_id", "episode_number", "language", name="uq_episodes_slot_language"
        ),
    )
    op.create_index("ix_episodes_season", "episodes", ["season_id"])
    op.create_index("ix_episodes_status", "episodes", ["status"])
    op.create_index("ix_episodes_language", "episodes", ["language"])
    op.create_index("ix_episodes_content_group", "episodes", ["content_group"])
    # The rule from the brief. Partial, because NULL means "not part of a group"
    # and a plain unique index would let exactly one ungrouped episode exist per
    # language across the entire catalogue.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_episodes_group_language
            ON episodes (content_group, language)
            WHERE content_group IS NOT NULL
        """
    )

    op.create_table(
        "artworks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("owner_type", sa.String(16), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("url", sa.String(1024), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(64), nullable=False),
        sa.Column("original_filename", sa.String(255)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("owner_type in ('show','episode')", name="ck_artworks_owner_type"),
        sa.CheckConstraint("kind in ('poster','banner','thumbnail')", name="ck_artworks_kind"),
        sa.UniqueConstraint("owner_type", "owner_id", "kind", name="uq_artworks_slot"),
    )
    op.create_index("ix_artworks_owner", "artworks", ["owner_type", "owner_id"])

    op.create_table(
        "publish_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "actor_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
        ),
        sa.Column("actor_email", sa.String(255)),
        sa.Column("status", sa.String(16), nullable=False, server_default="running"),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("counts", postgresql.JSONB()),
        sa.Column("error", sa.Text()),
        sa.Column("catalog_key", sa.String(512)),
        sa.Column("catalog_checksum", sa.String(64)),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.CheckConstraint("status in ('running','success','failed')", name="ck_publish_runs_status"),
    )
    op.create_index("ix_publish_runs_started", "publish_runs", ["started_at"])
    # "Two catalogues are live at once" is the bug that would be hardest to
    # notice and worst to debug, so it is made unrepresentable.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_publish_runs_current
            ON publish_runs (is_current)
            WHERE is_current
        """
    )

    op.create_table(
        "catalog_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("publish_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("show_slug", sa.String(160), nullable=False),
        sa.Column("show_title", sa.String(255), nullable=False),
        sa.Column("section", sa.String(64), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String(64)), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String(16)), nullable=False),
        sa.Column("episode_title", sa.String(255)),
        sa.Column("season_number", sa.Integer()),
        sa.Column("episode_number", sa.Integer()),
        sa.Column("sort_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.CheckConstraint("kind in ('show','episode')", name="ck_catalog_entries_kind"),
    )
    # Every search pins the run first, so run_id leads each index.
    op.create_index("ix_catalog_entries_run", "catalog_entries", ["run_id", "kind"])
    op.create_index(
        "ix_catalog_entries_run_section", "catalog_entries", ["run_id", "section", "sort_index"]
    )
    op.create_index("ix_catalog_entries_run_slug", "catalog_entries", ["run_id", "show_slug"])
    op.create_index(
        "ix_catalog_entries_categories", "catalog_entries", ["categories"], postgresql_using="gin"
    )
    op.create_index(
        "ix_catalog_entries_languages", "catalog_entries", ["languages"], postgresql_using="gin"
    )
    op.execute(
        """
        CREATE INDEX ix_catalog_entries_search_trgm
            ON catalog_entries USING gin (search_text gin_trgm_ops)
        """
    )

    op.create_table(
        "import_rejects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("source_ref", sa.String(128)),
        sa.Column("reason_code", sa.String(64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("resolved", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_import_rejects_resolved", "import_rejects", ["resolved"])


def downgrade() -> None:
    op.drop_table("import_rejects")
    op.drop_table("catalog_entries")
    op.drop_table("publish_runs")
    op.drop_table("artworks")
    op.drop_table("episodes")
    op.drop_table("seasons")
    op.drop_table("shows")
    op.drop_table("users")
